---
apiVersion: v1
kind: Pod
metadata:
  name: red-leader
  labels:
    org: alliance
    class: x-wing
spec:
    containers:
      - name: x-wing
        image: nicolaka/netshoot:latest
        imagePullPolicy: Always
        command: ["sleep", "infinite"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: millenium-falcon
  labels:
    org: alliance
    class: yt-1300f
spec:
    containers:
      - name: x-wing
        image: nicolaka/netshoot:latest
        imagePullPolicy: Always
        command: ["sleep", "infinite"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: luke
  labels:
    org: alliance
    class: x-wing
spec:
    containers:
      - name: x-wing
        image: nicolaka/netshoot:latest
        imagePullPolicy: Always
        command: ["sleep", "infinite"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: darth-vader
  labels:
    org: empire
    class: tiefighter
spec:
    containers:
      - name: x-wing
        image: nicolaka/netshoot:latest
        imagePullPolicy: Always
        command: ["sleep", "infinite"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
---
apiVersion: v1
kind: Pod
metadata:
  name: obi-wan
  labels:
    org: alliance
    class: ghost
spec:
    containers:
      - name: x-wing
        image: nicolaka/netshoot:latest
        imagePullPolicy: Always
        command: ["sleep", "infinite"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
