---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: rackX
spec:
  nodeSelector:
    matchLabels:
      rack: rackX
  virtualRouters:
  - localASN: ABC
    exportPodCIDR: true
    neighbors:
    - peerAddress: "X/32"
      peerASN: DEF 